### PR TITLE
Lazy connections

### PR DESCRIPTION
**Pull request by krzysztof-gzocha**

### CODE REVIEW

**Comment by krzysztof-gzocha** [comment]
@thomasvargiu Tests are failing for me even on master branch. Should I do something not specified in README in order to fix it?

**Comment by thomasvargiu** [comment]
@krzysztof-gzocha Sorry, I can't merge this. You are using another logic to implement another connection type.
If you want to add the `AMQPLazyConnection` you should create a factory `RabbitMqModule\Service\Connection\LazyConnectionFactory`.
Then you can add it on `RabbitMqModule\Service\ConnectionFactory::$factoryMap`:

``` php
    /**
     * @var array
     */
    protected $factoryMap = [
        'stream' => 'RabbitMqModule\\Service\\Connection\\StreamConnectionFactory',
        'socket' => 'RabbitMqModule\\Service\\Connection\\SocketConnectionFactory',
        'ssl' => 'RabbitMqModule\\Service\\Connection\\SSLConnectionFactory',
        'lazy' => 'RabbitMqModule\\Service\\Connection\\LazyConnectionFactory',
    ];
```

**Comment by krzysztof-gzocha** [comment]
Good point. Will fix it and open it in another PR

**Comment by thomasvargiu** [comment]
@krzysztof-gzocha Sorry, I re-open this pull request, it's ok here.

**Comment by krzysztof-gzocha** [comment]
Great, but there is still problem with tests.. Do you have any idea what might be wrong?

**Comment by thomasvargiu** [comment]
I need to check. But probably it's a dependency compatibility problem.

**Comment by krzysztof-gzocha** [comment]
Ok, @thomasvargiu. Let me know if there is anything more that I can do with this PR.

**Comment by krzysztof-gzocha** [comment]
@thomasvargiu any update in this topic?

**Comment by thomasvargiu** [comment]
@krzysztof-gzocha Can you rebase it with the master branch? I've fixed the tests.
It was a problem with some `E_USER_DEPRECATION` triggered in zend-mvc.

**Comment by krzysztof-gzocha** [comment]
Ok. Thank you for information.

**Comment by krzysztof-gzocha** [comment]
@thomasvargiu done. Tests are passing again. Good job!

**Comment by thomasvargiu** [comment]
@krzysztof-gzocha Merged! Thank you!

**Pull request merged**
